DATASET:
  root_dir: /data/semanticKITTI/dataset
  type: SemanticKITTI
  augmentation:
    flips: true

MODEL:
  type: LMSCNet
  num_classes: 20
  voxel_dims: [256, 256, 32]

TRAIN:
  # Dataloader
  batch_size: 4
  num_workers: 4
  # Trainer
  epochs: 80
  learning_rate: 0.001
  summary_period: 10 # [batch]
  checkpoint_period: 15 # [epoch]
  validation_summary_period: 1 # [epoch]
  # Optimizer
  type: Adam # [Adam, SGD]
  Adam_beta1: 0.9
  Adam_beta2: 0.999
  SGD_momentum: NA
  SGD_weight_decay: NA
  # Scheduler
  scheduler: None # [None, constant, power_iteration]
  scheduler_frequency: epoch
  lr_power: 0.98

LOSS:
  base_type: CrossEntropyLoss
  weight: None

LOGGER:
  log_dir: experiments
  timezone: Asia/Seoul # see https://docs.python.org/3.13/library/zoneinfo.html#module-zoneinfo

