DATALOADER:
  num_workers: 4
DATASET:
  augmentation:
    flips: true
  modalities:
    3d_label: true
    3d_occluded: true
    3d_occupancy: true
  root_dir: /data/semanticKITTI/dataset
  type: SemanticKITTI
MODEL:
  type: LMSCNet
OPTIMIZER:
  type: Adam # [Adam, SGD]
  learning_rate: 0.001
  Adam_beta1: 0.9 # Adam beta1
  Adam_beta2: 0.999 # Adam beta2
  SGD_momentum: NA
  SGD_weight_decay: NA
  scheduler: None # [None, constant, power_iteration]
  frequency: epoch
  lr_power: 0.98
OUTPUT:
  best_loss: 999999999999
  best_metric: -999999999999
  output_path: ../SSC_out/LMSCNet_SemanticKITTI_1101_071003
  out_root: ../SSC_out/
STATUS:
  config: SSC_configs/examples/LMSCNet.yaml
  last: ""
  resume: false
TRAIN:
  epochs: 80
  batch_size: 4
  checkpoint_period: 15
  summary_period: 50
  # Optimizer
  optimizer: Adam # [Adam, SGD]
  learning_rate: 0.001
  Adam_beta1: 0.9
  Adam_beta2: 0.999
  SGD_momentum: NA
  SGD_weight_decay: NA
  # Scheduler
  scheduler: # [None, constant, power_iteration] Leave empty for no scheduler

VAL:
  batch_size: 8
  summary_period: 20
